#!/bin/sh

BASEDIR=$(dirname $(realpath "$0"))

SERVERS=`echo "jrpcserver egress ingress"`
echo "Building rpc-relay..."

for srv in $SERVERS; do
  eval "${BASEDIR}/buildsrv ${srv}"
done

echo "Build finished"